---
- name: Create filesystem
  ansible.posix.filesystem:
    fstype: "{{ fstype }}"
    dev: "/dev/{{ active_vg }}/{{ lv_name }}"

- name: Mount filesystem and add fstab entry
  ansible.posix.mount:
    path: "{{ mount_point }}"
    src: "/dev/{{ active_vg }}/{{ lv_name }}"
    fstype: "{{ fstype }}"
    state: mounted

