#SPDX-License-Identifier: MIT-0
---
# tasks file for filesystem_provision
- name: Assert mandatory variables
  ansible.builtin.include_tasks: 01_assert.yml

- name: Discover existing storage
  ansible.builtin.include_tasks: 02_discover.yml

- name: Provision storage
  ansible.builtin.include_tasks: 03_provision.yml

- name: Create filesystem and mount
  ansible.builtin.include_tasks: 04_filesystem.yml
